[package]
name = "subspace-data-retrieval"
description = "Fetching data from the archived history of the Subspace Distributed Storage Network."
license = "0BSD"
version = "0.1.0"
authors = ["Teor <teor@riseup.net>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
anyhow = "1.0.89"
async-trait = "0.1.83"
futures = "0.3.31"
hex = "0.4.3"
parity-scale-codec = { version = "3.6.12", features = ["derive"] }
subspace-archiving = { version = "0.1.0", path = "../../crates/subspace-archiving" }
subspace-core-primitives = { version = "0.1.0", path = "../../crates/subspace-core-primitives" }
subspace-runtime-primitives = { version = "0.1.0", path = "../../crates/subspace-runtime-primitives" }
subspace-erasure-coding = { version = "0.1.0", path = "../../crates/subspace-erasure-coding" }
thiserror = "2.0.0"
tokio = { version = "1.40.0", features = ["sync"] }
tracing = "0.1.40"

[dev-dependencies]
rand = { version = "0.8.5", features = ["min_const_gen"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }

[features]
parallel = [
    "subspace-archiving/parallel",
]
