[package]
name = "subspace-gateway"
version = "0.1.0"
authors = [
    "Teor <teor@riseup.net>",
    "Shamil Gadelshin <shamilgadelshin@gmail.com>"
]
description = "A Subspace Network data gateway."
edition = "2021"
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md"
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
actix-web = { version = "4", features = ["rustls"], default-features = false }
async-lock = "3.4.0"
anyhow = "1.0.89"
async-trait = "0.1.83"
clap = { version = "4.5.18", features = ["derive"] }
fdlimit = "0.3.0"
futures = "0.3.31"
hex = "0.4.3"
jsonrpsee = { version = "0.24.5", features = ["server", "ws-client"] }
mimalloc = "0.1.43"
reqwest = { version = "0.12.9", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-data-retrieval = { version = "0.1.0", path = "../../shared/subspace-data-retrieval" }
subspace-gateway-rpc = { version = "0.1.0", path = "../subspace-gateway-rpc" }
subspace-kzg = { version = "0.1.0", path = "../../shared/subspace-kzg" }
subspace-logging = { version = "0.0.1", path = "../../shared/subspace-logging" }
subspace-networking = { version = "0.1.0", path = "../subspace-networking" }
subspace-rpc-primitives = { version = "0.1.0", path = "../subspace-rpc-primitives" }
subspace-verification = { version = "0.1.0", path = "../subspace-verification", default-features = false }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "signal", "macros"] }
tracing = "0.1.40"
